<?php

/**
 * @file
 * Module file for the GDPR Consent module.
 */

use Drupal\Core\Url;

/**
 * Implements hook_toolbar_alter().
 */
function gdpr_consent_toolbar_alter(&$items) {
  $user = \Drupal::currentUser();

  if ($user->hasPermission('manage gdpr agreements')) {
    $items['gdpr']['tray']['links']['#links']['agreements'] = [
      'title' => t('Agreements'),
      'url' => Url::fromRoute('entity.gdpr_consent_agreement.collection'),
      'attributes' => [
        'title' => t('Consent Agreements'),
      ],
      'weight' => 100,
    ];
  }
}
